@startuml
!include <aws/common>
skinparam componentStyle rectangle

component "pocket-docker CLI" as CLI
component "runtime" as RT
component "store" as ST
component "logging" as LG
node "Linux Kernel" as K

CLI --> RT : run/stop/ps
RT --> K : namespaces, cgroups
RT --> ST : zapisywanie stanu
RT --> LG : logi
CLI --> ST : pull / rm
CLI --> LG : logs
@enduml