@startuml
actor User
participant CLI
participant Runtime
participant Kernel
participant Store
User -> CLI : run
CLI -> Runtime : create namespaces
Runtime -> Kernel : clone
Runtime -> Store : save info
Runtime -> Kernel : exec command
CLI <-- Runtime : container ID
@enduml